using TestItemRunner


# Cross-validation of the GluedSeam Hilbert curve against committed reference
# vectors produced by the HilbertCurveCompact Zig engine. This is a pure file
# check: no ccall, no Zig dependency. The vector file is regenerated by
# gen/generate_reference_vectors.jl (which is where the Zig comparison lives).
@testitem "GluedSeam matches Zig reference vectors" begin
    using BijectiveHilbert: GluedSeam, encode_hilbert_zero, decode_hilbert_zero!,
                            index_type, axis_type

    vecfile = joinpath(@__DIR__, "glued_seam_vectors.txt")
    @test isfile(vecfile)

    # Parse a header line: "# m=4,3,2 gray=random path=catalog gi=0 pi=3".
    function parse_header(line)
        body = strip(line[2:end])          # drop leading '#'
        m = Int[]
        gray = :brgc; path = :standard; gi = 0; pi = 0
        for tok in split(body)
            key, val = split(tok, "="; limit = 2)
            if key == "m"
                m = parse.(Int, split(val, ","))
            elseif key == "gray"
                gray = Symbol(val)
            elseif key == "path"
                path = Symbol(val)
            elseif key == "gi"
                gi = parse(Int, val)
            elseif key == "pi"
                pi = parse(Int, val)
            end
        end
        return (m, gray, path, gi, pi)
    end

    # Walk the file once, checking every point. Wrapped in a function so the
    # for-loop can update the running counters (top-level loops in the testitem
    # module are a hard scope).
    function check_vectors(path)
        g = nothing
        T = UInt64
        B = UInt8
        n = 0
        nblocks = 0
        nlines = 0
        bad_encode = 0
        bad_decode = 0
        first_fail = ""

        for raw in eachline(path)
            line = rstrip(raw)
            isempty(line) && continue
            if startswith(line, "#")
                # A config header starts with "# m="; other '#' lines are prose.
                if startswith(strip(line[2:end]), "m=")
                    m, gray, path2, gi, pi = parse_header(line)
                    g = GluedSeam(m; gray = gray, path = path2, gray_index = gi, path_index = pi)
                    T = index_type(g)
                    B = axis_type(g)
                    n = length(m)
                    nblocks += 1
                end
                continue
            end

            g === nothing && continue
            fields = split(line)
            @assert length(fields) == n + 1 "malformed data line: $line"
            X = B[parse(B, fields[i]) for i in 1:n]
            h_expected = parse(UInt128, fields[end]; base = 16)

            jh = encode_hilbert_zero(g, X)
            if UInt128(jh) != h_expected
                bad_encode += 1
                isempty(first_fail) && (first_fail = "encode $(g) X=$(Int.(X)) got=$(UInt128(jh)) want=$h_expected")
            end

            Y = zeros(B, n)
            decode_hilbert_zero!(g, Y, T(h_expected))
            if Y != X
                bad_decode += 1
                isempty(first_fail) && (first_fail = "decode $(g) h=$h_expected got=$(Int.(Y)) want=$(Int.(X))")
            end
            nlines += 1
        end
        return (nblocks, nlines, bad_encode, bad_decode, first_fail)
    end

    nblocks, nlines, bad_encode, bad_decode, first_fail = check_vectors(vecfile)

    if !isempty(first_fail)
        @info "First GluedSeam vector failure" first_fail
    end
    @test nblocks == 47
    @test nlines == 38596
    @test bad_encode == 0
    @test bad_decode == 0
end
